os: linux
language: node_js
node_js:
  - 15
branches:
  only:
    - staging
install:
  - yarn install
script:
  - yarn test
deploy:
  provider: heroku
  api_key: ...
  app: tutor-finder-server
  on: staging
