os: linux
language: node_js
node_js:
  - 15
  - node
services:
  - postgresql
branches:
  only:
    - staging
install:
  - yarn install
before_script:
  - node ace migration:rollback
script:
  - yarn test
after_script:
  - node ace migration:run
